# Generated by Django 3.1.3 on 2020-12-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProccesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('filter_low', models.FloatField()),
                ('filter_high', models.FloatField()),
                ('psd_freq', models.CharField(max_length=100)),
                ('split_persent', models.FloatField()),
                ('svm_c', models.FloatField()),
                ('svm_l1', models.FloatField()),
                ('svm_l2', models.FloatField()),
                ('result_acc', models.FloatField(null=True)),
                ('result_loss', models.FloatField(null=True)),
                ('result_f1_score', models.FloatField(null=True)),
                ('img_url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
